" to avoid side effects when reloading vimrc, only set nocp when needed
if &compatible | set nocompatible | endif

let $VIMPATH = $HOME . '/.vim'
let $CFGPATH = $VIMPATH . '/config'

function! s:source_cfg(path)
  execute 'source' fnameescape($CFGPATH . '/' . a:path)
endfunction

call s:source_cfg('reset.vim')
call s:source_cfg('base.vim')
call s:source_cfg('filetypes.vim')
call s:source_cfg('plug.vim')
call s:source_cfg('functions.vim')
call s:source_cfg('editing.vim')
call s:source_cfg('display.vim')
call s:source_cfg('shortcuts.vim')
call s:source_cfg('plugins.vim')
call s:source_cfg('terminal.vim')

" workaround for https://github.com/vim/vim/issues/6736
let g:arpeggio_timeoutlen = 34
silent! call arpeggio#load()
silent! Arpeggio noremap jk <ESC>
silent! Arpeggio inoremap jk <ESC>
silent! Arpeggio cnoremap jk <C-C>

" vim: set filetype=vim foldmethod=marker foldlevel=0 nowrap:
