" to avoid side effects when reloading vimrc, only set nocp when needed
if &compatible | set nocompatible | endif

let $VIMPATH = $HOME . '/.vim'
let $CFGPATH = $VIMPATH . '/config'

function! s:SourceConfig(path) abort
  execute 'source' fnameescape($CFGPATH . '/' . a:path)
endfunction

call s:SourceConfig('reset.vim')
call s:SourceConfig('base.vim')
call s:SourceConfig('filetypes.vim')
call s:SourceConfig('functions.vim')
call s:SourceConfig('editing.vim')
call s:SourceConfig('display.vim')
call s:SourceConfig('shortcuts.vim')
call s:SourceConfig('pkgr.vim')
call s:SourceConfig('plugins.vim')
call s:SourceConfig('terminal.vim')

if has('autocmd')
  filetype plugin indent on
endif
if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

" vim: set filetype=vim foldmethod=marker foldlevel=0 nowrap:
