#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# battery: show battery remaining
# ----------------------------------------------------------------------------

echo "ϟ$(pmset -g batt | awk 'NR==2 {print $3}' | sed 's/%.*$//')%"

# vim: set filetype=sh foldmethod=marker foldlevel=0 nowrap:
