#!/bin/bash

# ----------------------------------------------------------------------------
# interface: show inet interface
# ----------------------------------------------------------------------------

set -o pipefail

main() {
  netstat -rn \
    | grep default \
    | awk '{print $NF}' \
    | head -1
}

main

# vim: set filetype=sh foldmethod=marker foldlevel=0 nowrap:
