#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# localip: show local IP address
# ----------------------------------------------------------------------------

main() {
  local _interface
  _interface="${1:-$INTERFACE}"
  if [[ -n "$_interface" ]]; then
    ipconfig getifaddr "$_interface"
  else
    exit 1
  fi
}

main "$1"
