#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# macaddr: show hardware MAC address
# ----------------------------------------------------------------------------

ifconfig "$INTERFACE" ether \
  | tail -n 1 \
  | awk '{print $2}'
