#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# publicip: show public IP address
# ----------------------------------------------------------------------------

set -o pipefail

main() {
  dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com | tr -d '=["]='
}

main

# vim: set filetype=sh foldmethod=marker foldlevel=0 nowrap:
