#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# set-macaddr: set MAC address
# ----------------------------------------------------------------------------

_usage() {
read -r -d '' _usage_string <<'EOF'
Usage:
  set-macaddr [-h|--help] <macaddr>
  set-macaddr d4:9a:20:11:44:26

Options:
  -h, --help  Show this help text
EOF
echo "$_usage_string"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      _usage
      exit 0
      ;;
    *)
      _macaddr="$1"
      break
      ;;
  esac
done

if ! [[ -n "$_macaddr" ]]; then
  _usage
  exit 1
fi

main() {
  if ! [[ "$UID" == '0' ]]; then
    echo 'Sorry, requires root privileges'
    exit 1
  fi
  if ! [[ -n "$INTERFACE" ]]; then
    echo 'Sorry, requires $INTERFACE be set'
    exit 1
  fi
  networksetup -setairportpower "$INTERFACE" off
  ifconfig "$INTERFACE" down
  ifconfig "$INTERFACE" ether "$1"
  networksetup -detectnewhardware
}

main "$_macaddr"
