#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# set-macaddr: set MAC address on interface
# ----------------------------------------------------------------------------

_usage() {
read -r -d '' _usage_string <<'EOF'
Usage:
  set-macaddr [-h|--help] <interface> <macaddr>
  set-macaddr en0 d4:9a:20:11:44:26

Options:
  -h, --help  Show this help text
EOF
echo "$_usage_string"
}

_POSITIONAL=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      _usage
      exit 0
      ;;
    *)
      _POSITIONAL+=("$1")
      shift
      ;;
  esac
done

_interface="${_POSITIONAL[0]}"
_macaddr="${_POSITIONAL[1]}"

# restore positional params
set -- "${_POSITIONAL[@]}"

if ! [[ -n "$_macaddr" && -n "$_interface" ]]; then
  _usage
  exit 1
fi

main() {
  if ! [[ "$UID" == '0' ]]; then
    echo 'Sorry, requires root privileges'
    exit 1
  fi
  ifconfig "$1" down
  ifconfig "$1" ether "$2"
  networksetup -detectnewhardware
  ifconfig "$1" up
}

main "$_interface" "$_macaddr"
