timezones = [
    'UTC',
    'Asia/Jerusalem',
    'Asia/Riyadh',
    'Asia/Tehran',
    'Asia/Dubai',
    'Asia/Kolkata',
    'Asia/Kathmandu',
    'Asia/Novosibirsk',
    'Asia/Bangkok',
    'Asia/Kuala_Lumpur',
    'Asia/Singapore',
    'Asia/Phnom_Penh',
    'Asia/Jakarta',
    'Asia/Saigon',
    'Asia/Ulaanbaatar',
    'Asia/Hong_Kong',
    'Asia/Manila',
    'Asia/Shanghai',
    'Asia/Taipei',
    'Asia/Seoul',
    'Asia/Tokyo',
    'Australia/Perth',
    'Australia/Darwin',
    'Australia/Adelaide',
    'Australia/Brisbane',
    'Australia/Sydney',
    'Pacific/Auckland',
    'Pacific/Tahiti',
    'Pacific/Honolulu',
    'America/Anchorage',
    'America/Juneau',
    'America/Vancouver',
    'America/Phoenix',
    'America/Denver',
    'America/Chicago',
    'America/Mexico_City',
    'America/Montreal',
    'America/Panama',
    'America/Lima',
    'America/Santiago',
    'America/Bogota',
    'America/Caracas',
    'Atlantic/Bermuda',
    'America/Argentina/Buenos_Aires',
    'America/Asuncion',
    'America/Montevideo',
    'America/Sao_Paulo',
    'Atlantic/Reykjavik',
    'Europe/Dublin',
    'Europe/London',
    'Atlantic/Canary',
    'Europe/Lisbon',
    'Europe/Amsterdam',
    'Europe/Berlin',
    'Europe/Prague',
    'Europe/Belgrade',
    'Europe/Budapest',
    'Europe/Warsaw',
    'Europe/Helsinki',
    'Europe/Athens',
    'Europe/Bucharest',
    'Europe/Istanbul',
    'Europe/Moscow'
]
